package si.pecan.upsert.repository

import org.springframework.data.jpa.repository.support.SimpleJpaRepository
import org.springframework.data.repository.core.EntityInformation
import javax.persistence.EntityManager
import javax.persistence.Table

/**
 * Implementation of BaseUpsertRepository.
 * This class provides the implementation for the upsert and upsertAll methods.
 *
 * @param T The entity type
 * @param ID The type of the entity's ID
 */
class BaseUpsertRepositoryImpl<T : Any, ID : Any>(
    entityInformation: EntityInformation<T, ID>,
    private val entityManager: EntityManager
) : SimpleJpaRepository<T, ID>(entityInformation.javaType, entityManager), BaseUpsertRepository<T, ID> {

    private lateinit var upsertOperations: UpsertOperations

    // Cache for table names by entity class
    private val tableNameCache = mutableMapOf<Class<*>, String>()

    /**
     * Perform an upsert operation for the given entity.
     *
     * @param entity The entity to upsert
     * @return The updated entity with any autogenerated fields
     */
    override fun upsert(entity: T): T {
        val tableName = getTableName(entity.javaClass)
        return upsertOperations.upsert(entity, tableName)
    }

    /**
     * Perform an upsert operation for the given list of entities.
     *
     * @param entities The list of entities to upsert
     * @return The list of updated entities with any autogenerated fields
     */
    override fun upsertAll(entities: List<T>): List<T> {
        if (entities.isEmpty()) {
            return emptyList()
        }

        val tableName = getTableName(entities.first().javaClass)
        return upsertOperations.upsertAll(entities, tableName)
    }

    /**
     * Perform an upsert operation for the given entity with custom ON clause and ignored fields.
     *
     * @param entity The entity to upsert
     * @param onFields The fields to use for the ON clause
     * @param ignoredFields The fields to ignore during updates
     * @param ignoreAllFields Whether to ignore all fields during updates
     * @return The updated entity with any autogenerated fields
     */
    override fun upsert(
        entity: T,
        onFields: List<String>,
        ignoredFields: List<String>,
        ignoreAllFields: Boolean
    ): T {
        val tableName = getTableName(entity.javaClass)
        return upsertOperations.upsert(entity, tableName, onFields, ignoredFields, ignoreAllFields)
    }

    /**
     * Perform an upsert operation for the given list of entities with custom ON clause and ignored fields.
     *
     * @param entities The list of entities to upsert
     * @param onFields The fields to use for the ON clause
     * @param ignoredFields The fields to ignore during updates
     * @param ignoreAllFields Whether to ignore all fields during updates
     * @return The list of updated entities with any autogenerated fields
     */
    override fun upsertAll(
        entities: List<T>,
        onFields: List<String>,
        ignoredFields: List<String>,
        ignoreAllFields: Boolean
    ): List<T> {
        if (entities.isEmpty()) {
            return emptyList()
        }

        val tableName = getTableName(entities.first().javaClass)
        return upsertOperations.upsertAll(entities, tableName, onFields, ignoredFields, ignoreAllFields)
    }

    /**
     * Get the table name for the given entity class.
     * Uses a cache to avoid repeated lookups.
     *
     * @param entityClass The entity class
     * @return The table name
     */
    private fun getTableName(entityClass: Class<*>): String {
        // Check the cache first
        return tableNameCache.getOrPut(entityClass) {
            // Try to get the table name from @Table annotation
            val tableAnnotation = entityClass.getAnnotation(Table::class.java)
            if (tableAnnotation != null && tableAnnotation.name.isNotBlank()) {
                return@getOrPut tableAnnotation.name
            }

            // Try to get the table name from JPA entity metadata
            val entities = entityManager.metamodel.entities
            for (entity in entities) {
                if (entity.javaType == entityClass) {
                    return@getOrPut entity.name.lowercase()
                }
            }

            // Fallback to class name
            entityClass.simpleName.lowercase()
        }
    }
}
