name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.REPOSITORY_BUTLER_APP_ID }}
          private-key: ${{ secrets.REPOSITORY_BUTLER_PEM }}
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ steps.generate-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
